# Build and publish for each push  to branch master

name: GitHub Actions - Tagged release

on:
  push:
    branches:
      - 'master'

jobs:
  build-and-publish-master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '8'
          cache: 'gradle'

      - name: 'Build'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew build publish --no-daemon
