name: GitHub Actions - Build
on:
  push:
    branches:
      - 'dev'

jobs:
  build-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '8'
          cache: 'gradle'
      - name: 'Build'
        run: ./gradlew build --no-daemon